apiVersion: v1
kind: Service
metadata:
  labels:
    run: plantuml
  name: plantuml
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: plantuml
  type: LoadBalancer
